
name: flutter_wallaaha_v3_3
description: Complete version with modular UI and GPT-ready setup
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  archive: ^3.3.7
  http: ^0.13.6
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
