
// File generated by ChatGPT – Firebase config
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyALcO7h70ed8dodT8bAhxfdoFzyQfkTi_Q",
    authDomain: "wall3ha.firebaseapp.com",
    projectId: "wall3ha",
    storageBucket: "wall3ha.firebasestorage.app",
    messagingSenderId: "796416953634",
    appId: "1:796416953634:web:1e90fc8046b20e7b36a97b",
    measurementId: "G-XHCCMWNHD6",
  );
}
